; PlatformIO Project Configuration File
;
; Firmware target: ATtiny85, 8 MHz internal clock.
; Generic ATtiny85 uses the ATTinyCore Arduino framework in PlatformIO.

[env:attiny85]
platform = atmelavr@5.3.0
board = attiny85
framework = arduino
board_build.f_cpu = 8000000L
